# Spark config 2023-07-14
spark.executor.memory          4g
spark.executor.cores           2
spark.sql.shuffle.partitions   32
spark.streaming.kafka.maxRatePerPartition 1000
spark.sql.streaming.checkpointLocation /tmp/checkpoints
